// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieSeatBooking.Api.Infrastructure.Db;

#nullable disable

namespace MovieSeatBooking.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126102200_AddBookingScreeningSchema")]
    partial class AddBookingScreeningSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Bookings.BookedSeatEntity", b =>
                {
                    b.Property<Guid>("ScreeningId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("TEXT");

                    b.HasKey("ScreeningId", "SeatNumber");

                    b.HasIndex("BookingId");

                    b.ToTable("BookedSeats", (string)null);
                });

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Bookings.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScreeningId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Movies.MovieEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Screenings.ScreeningEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Screens.ScreenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Bookings.BookedSeatEntity", b =>
                {
                    b.HasOne("MovieSeatBooking.Api.Domain.Bookings.BookingEntity", "Booking")
                        .WithMany("Seats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Screenings.ScreeningEntity", b =>
                {
                    b.HasOne("MovieSeatBooking.Api.Domain.Screens.ScreenEntity", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("MovieSeatBooking.Api.Domain.Bookings.BookingEntity", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
